DROP TABLE IF EXISTS bitacora_actividad CASCADE;

DROP TABLE IF EXISTS cierres_caja CASCADE;
DROP TABLE IF EXISTS gastos CASCADE;

DROP TABLE IF EXISTS pagos CASCADE;

DROP TABLE IF EXISTS detalle_venta CASCADE;
DROP TABLE IF EXISTS ventas CASCADE;

DROP TABLE IF EXISTS movimientos_inventario CASCADE;
DROP TABLE IF EXISTS productos CASCADE;

DROP TABLE IF EXISTS usuarios CASCADE;
DROP TABLE IF EXISTS roles CASCADE;

DROP TABLE IF EXISTS sucursales CASCADE;